### ISSUE TITLE
Line Parser does not ignore Unicode's files BOM

### ISSUE THREAD

**Issue by kariem2k** [kariem2k/ref_parsers#1]
def open(filename)
      parse File.read(filename, encoding: 'UTF-8')
    end

    def parse(body)
      lines = body.split(/\n\r|\r\n|\n|\r/)

If the file has BOM bytes it will be considered as part of first line.
Example: export.ris

**Comment by kariem2k** [comment]
Fixed by changing it to  parse File.read(filename, mode: 'r:bom|UTF-8')

**Comment by hammady** [comment]
@kariem2k This was taken care of in the consumer of this gem. However, that's a useful addition. Does it work in BOM, non-BOM and non-UTF-8 inputs?
